-- FRIDA canonical Cloud SQL schema.  JSON remains text to preserve the exact
-- append-only artifact payloads established in local SQLite history.
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS observations (source_id TEXT NOT NULL, content_hash TEXT NOT NULL, source_reference TEXT NOT NULL, source_date TEXT NOT NULL, observed_at TEXT NOT NULL, evidence_class TEXT NOT NULL, replay_sequence INTEGER NOT NULL, PRIMARY KEY(source_id,content_hash));
CREATE TABLE IF NOT EXISTS candidate_signals (signal_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, observed_hash TEXT NOT NULL, observed_date TEXT NOT NULL, deduplication_key TEXT NOT NULL UNIQUE, provenance_reference TEXT NOT NULL, replay_sequence INTEGER NOT NULL, triage_state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events (event_id BIGSERIAL PRIMARY KEY, occurred_at TEXT NOT NULL, event_type TEXT NOT NULL, source_id TEXT NOT NULL, detail TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS golden_path_runs (run_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, state TEXT NOT NULL, view_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS execution_attempts (execution_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, execution_mode TEXT NOT NULL, source_observation_mode TEXT NOT NULL, source_id TEXT NOT NULL, source_hash TEXT NOT NULL, candidate_signal_id TEXT NOT NULL REFERENCES candidate_signals(signal_id), evidence_hashes_json TEXT NOT NULL, scenario_contract_version TEXT NOT NULL, authorization_reference TEXT NOT NULL, original_execution_reference TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS execution_events (event_id BIGSERIAL PRIMARY KEY, execution_id TEXT NOT NULL REFERENCES execution_attempts(execution_id), occurred_at TEXT NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS foresight_source_states (source_state_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, bundle_id TEXT NOT NULL UNIQUE, contract_version TEXT NOT NULL, integrity_verified BOOLEAN NOT NULL, geography TEXT NOT NULL, geographic_confidence TEXT NOT NULL, temporal_reference TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS foresight_scenario_input_sets (scenario_input_set_id TEXT PRIMARY KEY, source_state_id TEXT NOT NULL REFERENCES foresight_source_states(source_state_id), created_at TEXT NOT NULL, eligibility_status TEXT NOT NULL, payload_json TEXT NOT NULL, decision_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS foresight_execution_events (event_id BIGSERIAL PRIMARY KEY, foresight_execution_id TEXT NOT NULL, occurred_at TEXT NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS foresight_executions (foresight_execution_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, source_state_id TEXT NOT NULL REFERENCES foresight_source_states(source_state_id), scenario_input_set_id TEXT NOT NULL, authorization_reference TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS observation_cycles (cycle_id TEXT PRIMARY KEY, started_at TEXT NOT NULL, completed_at TEXT, status TEXT NOT NULL, source_count INTEGER NOT NULL, candidate_count INTEGER NOT NULL DEFAULT 0, semantic_call_count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS observation_cycle_events (event_id BIGSERIAL PRIMARY KEY, cycle_id TEXT NOT NULL REFERENCES observation_cycles(cycle_id), occurred_at TEXT NOT NULL, event_type TEXT NOT NULL, message TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signals (signal_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, source_hash TEXT NOT NULL, source_reference TEXT NOT NULL, source_date TEXT NOT NULL, evidence_class TEXT NOT NULL, eligibility TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(source_id,source_hash));
CREATE TABLE IF NOT EXISTS attention_assessments (attention_id TEXT PRIMARY KEY, signal_id TEXT NOT NULL UNIQUE REFERENCES signals(signal_id), decision TEXT NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cases (case_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, case_mode TEXT NOT NULL, title TEXT NOT NULL, label TEXT NOT NULL, source_observation_mode TEXT NOT NULL, status TEXT NOT NULL, metadata_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS case_links (case_id TEXT NOT NULL REFERENCES cases(case_id), link_type TEXT NOT NULL, link_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(case_id,link_type,link_id));
CREATE TABLE IF NOT EXISTS governed_evidence_bundles (bundle_id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(case_id), created_at TEXT NOT NULL, integrity_verified BOOLEAN NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS case_execution_attempts (execution_id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(case_id), candidate_signal_id TEXT NOT NULL REFERENCES candidate_signals(signal_id), bundle_id TEXT NOT NULL REFERENCES governed_evidence_bundles(bundle_id), created_at TEXT NOT NULL, execution_mode TEXT NOT NULL, source_observation_mode TEXT NOT NULL, authorization_reference TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS case_execution_events (event_id BIGSERIAL PRIMARY KEY, execution_id TEXT NOT NULL REFERENCES case_execution_attempts(execution_id), occurred_at TEXT NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS execution_events_execution_idx ON execution_events(execution_id,event_id);
CREATE INDEX IF NOT EXISTS foresight_execution_events_execution_idx ON foresight_execution_events(foresight_execution_id,event_id);
CREATE INDEX IF NOT EXISTS observation_cycle_events_cycle_idx ON observation_cycle_events(cycle_id,event_id);
CREATE TABLE IF NOT EXISTS source_fabric_observations (source_observation_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, retrieved_at TEXT NOT NULL, source_timestamp TEXT, source_url TEXT NOT NULL, state_fingerprint_sha256 TEXT NOT NULL, classification TEXT NOT NULL, provenance_json TEXT NOT NULL, canonical_state_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS source_fabric_observations_source_idx ON source_fabric_observations(source_id,retrieved_at);
